1차원 배열

In [1]:
#1차원 배열
import numpy as np
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [2]:
np.ndim(A)

1

In [3]:
A.shape

(4,)

In [4]:
A.shape[0]

4

2차원 배열

In [5]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
np.ndim(B)

2

In [7]:
B.shape

(3, 2)

In [8]:
#2차원 행렬 곱
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [9]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [10]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [11]:
#다른 예
A = np.array([[1,2,3], [4,5,6]])
A.shape

(2, 3)

In [12]:
B = np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

In [13]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

신경망에서 행렬 곱

In [14]:
#입력 2개(2), 가중치 각각 3개씩(2,3) = 3
X = np.array([1, 2])
X.shape

(2,)

In [15]:
W = np.array([[1,3,5], [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [16]:
W.shape

(2, 3)

In [17]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
